### ISSUE TITLE
if dict are part of list, get_all_keys fails

### ISSUE THREAD

**Issue by anilfunde** [russellballestrini/nested-lookup#19]
Example -
 [
    {
        "listings": [
            {
                "name": "title",
                "postcode": "postcode",
                "full_address": "fulladdress",
                "city": "city",
                "lat": "latitude",
                "lng": "longitude"
            }
        ]
    }
]

- get_all_keys fails here

**Comment by rameshrvr** [comment]
Hi @anilfunde,
This issue has been fixed in PR #20. Please close this once you verified it in released build (0.2.14).

**Comment by russellballestrini** [comment]
The fix was merged. Closing issue
