### ISSUE TITLE
PyPi version

### ISSUE THREAD

**Issue by SPoket** [russellballestrini/nested-lookup#27]
Could you please release version with last merged PR?

**Comment by rameshrvr** [comment]
I think @russellballestrini seems unavailable. The PR for one issue is yet to be merged. Once it is done we can cut a release. @SPoket

**Comment by russellballestrini** [comment]
Hey @SPoket and @rameshrvr I'll review now.

**Comment by russellballestrini** [comment]
@SPoket I shipped your PR to pypi: https://pypi.org/project/nested-lookup/0.2.19/

@rameshrvr the remaining PRs all seem to conflict with master. We might need to rethink them or reimplement them since now we do not have a `run` or `run_count` parameter.
