### ISSUE TITLE
Annotations break compatibility with Python 2.x

### ISSUE THREAD

**Issue by cornazano** [russellballestrini/nested-lookup#31]
It looks like version 0.2.20 introduced the use of annotations on one function, and it causes a syntax error when running on Python 2.7. The classifiers still indicate it should be compatible with 2.6 and 2.7, and there isn't a python_requires argument passed to setup.

Is the break in Python 2.x compatibility intentional?

**Comment by russellballestrini** [comment]
that was _not_ intentional.

**Comment by russellballestrini** [comment]
@matheuslins could you please make sure your latest refactor supports both Python 2 and Python 3?

**Comment by russellballestrini** [comment]
@cornazano please pin to `0.2.19` until we have a chance to fix the regression. This library aims to support Python 2.7 indefinitely.

**Comment by cornazano** [comment]
I've already excluded 0.2.20, and will be able to pick up future releases without any issues. Thanks! :)

**Comment by russellballestrini** [comment]
@cornazano I have fixed the issue and cut a new release `0.2.21`. Sorry about that, I will take closer inspection the next time I cut a release. I hope I didn't cause any production trouble. Thank you for trusting our library!
