### ISSUE TITLE
get_occurrences_and_values throws when same value in multiple dicts

### ISSUE THREAD

**Issue by paultop6** [russellballestrini/nested-lookup#34]
```
l = [
{
  "item1": 1234,
  "item2": 5678,
  "item4": [1234, 9012]
},
{
  "item1": "abcd",
  "item2": "efgh",
  "item4": [1234, "adcf"]
}
]

get_occurrences_and_values(l, value=1234)
```

The code above will throw TypeError: 'NoneType' object is not iterable.
I beieve the recursive action is matching 1234 within the list of item4 of the second dict, where it should be matching the entire value, or perhaps some kinda of different behaviour.

**Comment by russellballestrini** [comment]
Help wanted on fixing this one!

* current tests: https://github.com/russellballestrini/nested-lookup/blob/master/test_nested_lookup.py#L12
* tips on getting pull requests approved: https://russell.ballestrini.net/tips-for-getting-pull-requests-approved/

**Comment by russellballestrini** [comment]
new fork:

* https://git.unturf.com/python/nested-lookup/-/issues
