### ISSUE TITLE
Request: Option to return the "path" to the key and the "nested dict" that represents the value

### ISSUE THREAD

**Issue by alxgross** [russellballestrini/nested-lookup#38]
Hello,

great lib. May I suggest to add a feature that would give me the path to the found value(s) as well.

**Comment by vipulgupta-cpi** [comment]
Hi,

Very helpful library. I'll also like to put the same request for getting the absolute path of the found values. In addition to this if possible can we also have lookup/search based on absolute path.

For example
>>> document = [ { 'taco' : 42 } , { 'salsa' : [ { 'burrito' : { 'taco' : 69 } } ] } ]
>>> from nested_lookup import nested_lookup
>>> print(nested_lookup('salsa.burrito.taco', document))
[69]

**Comment by russellballestrini** [comment]
new fork:

* https://git.unturf.com/python/nested-lookup/-/issues
