### ISSUE TITLE
search for the values instead of keys

### ISSUE THREAD

**Issue by namnamir** [russellballestrini/nested-lookup#4]
I am looking for a way to look for a certain keywords in a dict which are stored in values not keys.

[here](http://esprima.org/demo/parse.html?code=%2F%2F%20---------------------%0A%2F%2F%20Local%20Storage%20Syntax%0A%2F%2F%20---------------------%0A%2F%2F%20localStorage%0A%2F%2F%20sessionStorage%0A%2F%2F%20setItem%20(INSERT)%0A%2F%2F%20getItem%20(SELECT)%0A%2F%2F%20removeItem%20(DELETE)%0A%2F%2F%20clear%0A%0A%2F%2F%20*********%0A%2F%2F%20EXAMPLES%0A%2F%2F%20*********%0A%20%20%20%20%2F%2F%20Check%20if%20the%20localStorage%20object%20exists%0A%20%20%20%20if(localStorage)%7B%0A%20%20%20%20%20%20%20%20%2F%2F%20Store%20data%0A%20%20%20%20%20%20%20%20localStorage.setItem(%22first_name%22%2C%20%22Peter%22)%3B%0A%0A%20%20%20%20%20%20%20%20%2F%2F%20Retrieve%20data%0A%20%20%20%20%20%20%20%20alert(%22Hi%2C%20%22%20%2B%20localStorage.getItem(%22first_name%22))%3B%0A%20%20%20%20%7D%20else%7B%0A%20%20%20%20%20%20%20%20alert(%22Sorry%2C%20your%20browser%20do%20not%20support%20local%20storage.%22)%3B%0A%20%20%20%20%7D%0A%0A%09%09function%20clickCounter()%20%7B%0A%09%09if(typeof(Storage)%20!%3D%3D%20%22undefined%22)%20%7B%0A%09%09%09if%20(localStorage.clickcount)%20%7B%0A%09%09%09%09localStorage.clickcount%20%3D%20Number(localStorage.clickcount)%2B1%3B%0A%09%09%09%7D%20else%20%7B%0A%09%09%09%09localStorage.clickcount%20%3D%201%3B%0A%09%09%09%7D%0A%09%09%09document.getElementById(%22result%22).innerHTML%20%3D%20%22You%20have%20clicked%20the%20button%20%22%20%2B%20localStorage.clickcount%20%2B%20%22%20time(s).%22%3B%0A%09%09%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20document.getElementById(%22result%22).innerHTML%20%3D%20%22Sorry%2C%20your%20browser%20does%20not%20support%20web%20storage...%22%3B%0A%09%09%7D%0A%09%7D%0A%09%0A%09function%20storageAvailable(type)%20%7B%0A%09%09try%20%7B%0A%09%09%09var%20storage%20%3D%20window%5Btype%5D%2C%0A%09%09%09%09x%20%3D%20'__storage_test__'%3B%0A%09%09%09storage.setItem(x%2C%20x)%3B%0A%09%09%09storage.removeItem(x)%3B%0A%09%09%09return%20true%3B%0A%09%09%7D%0A%09%09catch(e)%20%7B%0A%09%09%09return%20e%20instanceof%20DOMException%20%26%26%20(%0A%09%09%09%09%2F%2F%20everything%20except%20Firefox%0A%09%09%09%09e.code%20%3D%3D%3D%2022%20%7C%7C%0A%09%09%09%09%2F%2F%20Firefox%0A%09%09%09%09e.code%20%3D%3D%3D%201014%20%7C%7C%0A%09%09%09%09%2F%2F%20test%20name%20field%20too%2C%20because%20code%20might%20not%20be%20present%0A%09%09%09%09%2F%2F%20everything%20except%20Firefox%0A%09%09%09%09e.name%20%3D%3D%3D%20'QuotaExceededError'%20%7C%7C%0A%09%09%09%09%2F%2F%20Firefox%0A%09%09%09%09e.name%20%3D%3D%3D%20'NS_ERROR_DOM_QUOTA_REACHED')%20%26%26%0A%09%09%09%09%2F%2F%20acknowledge%20QuotaExceededError%20only%20if%20there's%20something%20already%20stored%0A%09%09%09%09storage.length%20!%3D%3D%200%3B%0A%09%09%7D%0A%09%7D) is an example made by ESPrima. In this example I am looking for the occurrence of each of the following keywords (localstorage queries):
- "localStorage" 
- "sessionStorage"
- "setItem"
- "getItem"
- "removeItem"
- "clear"

do you have any solution for it?

**Comment by russellballestrini** [comment]
For keys, you can just use 
```
len(nested_lookup("localStorage", document))
```

For values, I think if you just need the occurrence of a string in general, you can cast the document (`dictionary`) to string and then use a `regex` and count the matches.

**Comment by rameshrvr** [comment]
@russellballestrini If you this think Pull Request: https://github.com/russellballestrini/nested-lookup/pull/6 will solve this issue. Then please close it after confirming with @namnamir

**Comment by russellballestrini** [comment]
Fixed in #6
