### ISSUE TITLE
Consider adding an (un)license file

### ISSUE THREAD

**Issue by bollwyvl** [russellballestrini/nested-lookup#41]
Thanks for this tool!

A little story: this was adopted by https://github.com/executablebooks/jupyter-book/pull/1123, which I'd like to re-package for [conda-forge](https://github.com/conda-forge/staged-recipes). Part of the process there requires _some_ kind of file which documents the rights that various parties (maintainers, users, repackagers) have with respect to the software. The words, "Public Domain," don't really have a well-established meaning across various legal boundaries, etc. which makes it hard for various entities to use the software.

It would be very helpful if an actual document was added to this repo, and better still, to source distributions. Some examples include:
- https://unlicense.org/
- https://spdx.org/licenses/CC-PDDC.html
- or really any of these that have Public Domain in them: https://spdx.org/licenses/

Happy to make a PR! (e.g. add file, `include` in `MANIFEST.in`)

**Comment by choldgraf** [comment]
Ping @russellballestrini in case he does not watch this repository. Really any license would be better than no license, so that others know what to expect from this useful repository! 🙂

**Comment by russellballestrini** [comment]
I don't feel compelled to act on this at this time.

**Comment by russellballestrini** [comment]
Please fork this repo if you want to license it or unlicense it. This copy is public domain.

**Comment by choldgraf** [comment]
Sounds good @russellballestrini, we will explore forking it in order to add a license if this is going to be a deal-breaker for the conda-forge distribution.

we saw the "public domain" bit but as @bollwyvl mentioned:

> The words, "Public Domain," don't really have a well-established meaning across various legal boundaries, etc. which makes it hard for various entities to use the software.

**Comment by russellballestrini** [comment]
new fork:

* https://git.unturf.com/python/nested-lookup/-/issues
