### ISSUE TITLE
Need volunteer to write a couple unit tests to prevent future regressions

### ISSUE THREAD

**Issue by russellballestrini** [russellballestrini/nested-lookup#42]
We caught a nasty edge case in pull request #36 but we never took the time to actually codify the test cases embedded in the comments. We really need somebody to add these test cases (and any others you can thing of) into our tests located here: 

* current tests: https://github.com/russellballestrini/nested-lookup/blob/master/test_nested_lookup.py#L12
* tips on getting pull requests approved: https://russell.ballestrini.net/tips-for-getting-pull-requests-approved/
* reference: https://github.com/russellballestrini/nested-lookup/pull/36 for hints on the defect we want to guard against.

**Comment by nileshfriendbuy** [comment]
- @russellballestrini I wanna volunteer and give this a try if you like. Thanks
- Might have a few questions along the way which I will send you your way if I end up doing this

**Comment by russellballestrini** [comment]
new fork:

* https://git.unturf.com/python/nested-lookup/-/issues
