### ISSUE TITLE
nested_alter isn't truly recursive

### ISSUE THREAD

**Issue by danhje** [russellballestrini/nested-lookup#43]
nested_alter fails to update elements deep in the hierarchy if the structure of the hierarchy higher up has been altered in the same call. Example:  

```python
from nested_lookup import nested_alter

def rename_subkeys(data):
    try:
        data['renamed'] = data.pop('rename me')
    except KeyError:
        pass
    return data


document = {'key': {'rename me': 1}, 'sub': {'key': {'rename me': 1}}}
altered_document = nested_alter(document, 'key', rename_subkeys)
# The above call works, since renaming the first key doesn't alter how the second key is accessed. Result:
# {'key': {'renamed': 1}, 'sub': {'key': {'renamed': 1}}}

document = {'key': {'rename me': {'rename me': 1}}}
altered_document = nested_alter(document, 'key', rename_subkeys)
# This does not work, only one of the keys are renamed. Result: 
# {'key': {'renamed': {'rename me': 1}}}
```

**Comment by danhje** [comment]
Thanks for merging in my PR! Any plans on doing a release to include this fix?

**Comment by russellballestrini** [comment]
Done, please let me know if it works. Might I ask what project you use `nested-lookup` in? Looking for Remote help?

**Comment by russellballestrini** [comment]
Please reopen if you have issues!

**Comment by danhje** [comment]
> Done, please let me know if it works. Might I ask what project you use `nested-lookup` in? Looking for Remote help?

Thanks again! Nested-lookup is being used in an internal library which converts pydantic schemas to avro schemas.
