### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by SuperSandro2000** [russellballestrini/nested-lookup#47]
It would be nice for downstream packaging if releases where tagged.

**Comment by russellballestrini** [comment]
yes, do u want admin on this repo?

**Comment by SuperSandro2000** [comment]
Na, I have enough projects which I maintain.

**Comment by russellballestrini** [comment]
same, also I forked over to gitlab

**Comment by russellballestrini** [comment]
this fork is dead, new fork:

https://git.unturf.com/python/nested-lookup/-/issues
